### ISSUE TITLE
package.json entry point is wrong

### ISSUE THREAD

**Issue by Kyry11** [erykpiast/angular-duration-format#8]
Hiya,

Thanks for the library!
It seems that I'm the first to use this library through npm. In your package.json you have wrong reference to the entry point: `"main": "gruntfile.js"`. This should point to the actual entry point in the compiled code. In your case this would be `"main": "dist/angular-duration-format.js",`.

Please fix and update NPM repo :)

**Comment by erykpiast** [comment]
Thak you for the report! I guess people used to use it with Bower so far, so they were not affected by this. I fixed it anyway in [v1.0.1](https://github.com/erykpiast/angular-duration-format/releases/tag/1.0.1). Could you please check if it works now for you?

**Comment by Kyry11** [comment]
Yes - everything seems to work now, thank you!
